language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vjunloc/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true vjunloc/react-test npm test

after_success:
  - docker build -t vjunloc/multi-client ./client
  - docker build -t vjunloc/multi-nginx ./nginx
  - docker build -t vjunloc/multi-server ./server
  - docker build -t vjunloc/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vjunloc/multi-client
  - docker push vjunloc/multi-nginx
  - docker push vjunloc/multi-server
  - docker push vjunloc/multi-worker

deploy:
  provicder: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-992382785958"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
